---
#settings
- An archaeological dig in the jungle
- The ruins of a great civilization
- A spaceship floating amongst the stars
- The depths of the jungle
- A star-lit night
- The opening night of a play
- The Village Fete
- As the sun rises
- As the sun sets
- In a village high in the mountains
- In the temple of an old god
- The night of the opening ball
- In the War Room
- On the fields of battle
- In a wooded glen
- High above the clouds
- In the gardens of a country manor
- On the brink of a new year
- An archaeological dig in the desert
- In the temple of vengeful god
- The ruins of a castle
- A city filled with canals
- A city where it always rains
- A land where it always snows
- A land with no sunlight
- A land with no darkness
- A land after the great fall of technology
- A town where everyone has a secret
- A university where there was a recent murder
- A capital city during it's social season
- A murder at a masque ball
- A masquerade after the unmasking
- The last dance at a ball
- A night at the opera
- Right before the world ends
- Right after the world ends
- An office building
- A bar after the war 
- A tavern in the woods
- A tavern on the outskirts of civilization
- An oasis in the middle of the day
- An oasis at night
- A bazaar
- A library beneath the sands
- A castle that moves
- A castle in the sky
- A monster's hideout
- A laboratory
- A wedding
- A wedding of an enemy
- A wedding of a former lover
- A festival of the harvest
- A night with no stars
- A night with no moon
- The feast hall after a fierce battle
- The feast hall after a poisoning
- An apothecary's shop
- The city just before dawn